//TIPOS DE DADOS PRIMITIVOS

/* 
TANTO UNDEFINED QUANTO NULL AMBOS NÃO APONTAM EM VALOR NENHUM NA MEMORIA
O NULL NOS UTILIZAMOS ELE QUANDO QUEREMOS DESCONFIGURAR O VALOR DE UMA VARIAVEL
A DIFERENÇA ENTRE UNDEFINED E NULL, E QUE O NULL NOS QUE COLOCAMOS ESSE VALOR LA DENTRO DA VARIAVEL
E NUNCA VAMOS SETAR UM VALOR DE UMA VARIAVEL COMO UNDEFINED O MOTOR DO JS QUE VAI FAZER ESSA VERIFICAÇÃO 
E DEVOLVER ESSE VALOR

*/

const nome = 'João' //STRING
const nome1 = "João" //STRING
const nome2 = `João` //STRING
const num1 = 10 //NUMBER
const num2 = 10.54 //NUMBER
let studentName; //UNDEFINE = NÃO APONTA EM LOCAL NENHUM NA MEMORIA
let studentSurname = null // NÃO APONTA EM LOCAL NENHUM NA MEMORIA
// const boolean = true or false O TIPO DE DADO BOOLEANO ELE VAI NOS RETORNAR APENAS TRUE OR FALSE E UM VALOR LOGICO

// const a = [1, 2]
// const b = a
// console.log(a, b)

// b.push(3)
// console.log(a, b)

let a = 2
const b = a
console.log(a,b) //2, 2

a = 3
console.log(a,b)//3, 2