//Let vs Var - A primeira diferença

/* 
QUANDO UTILIZAMOS VAR PARA PODER DECLARAR UMA VARIAVEL COM O MESMO NOME
ELA VAI ALTERAR O VALOR, MAS QUANDO FAZEMOS ISSO COM LET VAI APRESENTAR UM ERRO
ECMASCRIPT - E UMA PADRONIZAÇÃO DO JS FEITO PELA EMPRESA ECMA, MAS JS === ECMASCRIPT
NUNCA CRIAR UMA VARIAVEL SEM AS PALAVRAS CONST E LET
*/

// nome = 'Moura' NÃO PODEMOS FAZER ISSO
// var nome = 'João'
// var nome = 'Pedro'
// console.log(nome) COM VAR PODEMOS REDACLARAR UMA VARIAVEL MAS COM LET NÃO

// let nome = 'Afonso'
// let nome = 'Germano'
// console.log(nome)