//COMENTARIOS DE CODIGO 

/*
COMENTARIOS SÃO TRECHOS DE CODIGO QUE NÃO SÃO EXECUTADOS PELO MOTOR
DO JS, ELE VAI SER IGNORADO 
COM COMENTARIOS PODEMOS ESCREVER ANOTAÇÕES NO NOSSO CODIGO
E ELE NÃO VÃOI SER EXECUTADOS
TEMOS DUAS MANEIRAS DE FAZER COMENTARIOS: DESSA MANEIRA // OU /*
E UTILIZAMOS OS COMENTARIOS TAMBEM PARA QUE CERTOS TRECHOS DE CODIGO NÃO 
SEJAM EXIBIDOS 

*/


//UM EXEMPLO
console.log("Hello world!!!")
console.log("Linha 1") //IGNORADO
console.log("Linha 2") //IGNORADO
// console.log("Linha 3") //IGNORADO
