//FUNÇÃO CONSOLE.LOG
/* 
QUANDO QUISERMOS MOSTRAR ALGO NA TELA
DEVEMOS UTILIZAR A FUNÇÃO CONSOLE.LOG()
O ; NO JS E OPCIONAL
E PODEMOS COLOCAR QUALQUER COISA DENTRO
DA FUNÇÃO CONSOLE.LOG()
SEMPRE QUE FORMOS COLOCAR UM VALOR LITERAL,
DEVEMOS ENVOLVER ENTRE ASPAS PODENDO SER ASPAS "" OU ''
E SEMPRE DEVEMOS FECHAR COM A MESMA ASPAS QUE ABRIMOS
E PODEMOS USAR AS `` TAMBEM PARA EXIBIR UM VALOR LITERAL
TUDO QUE ESTIVER ENTRO '', "" OU `` E CONSIDERADO STRING = TEXTO
PARA EXIBIRMOS UM NUMERO NÃO PRECISAMOS COLOCAR AS ASPAS
TUDO E NUMBER EM JS, NÃO EXISTE A DISTINÇÃO ENTRE NUMERO NO JS
E A FUNÇÃO CONSOLE.LOG() ELA SO E EXIBIDA NO CONSOLE
*/

console.log('João Pedro');
console.log("João Pedro");
console.log(`João Pedro`); //UTILIZAMOS A CRASES PARA FAZERMOS ALGO CHAMADO TEMPLATE STRING

console.log("'João Pedro'"); //USANDO ASPAS SIMPLES DENTRO DE ASPAS DUPLAS
console.log('João "Pedro"'); //USANDO ASPAS DUPLAS DENTRO DE ASPAS DUPLAS
console.log(123456)
console.log(123.45, 6156.16, 1584851.4648) // ISSO E UM NUMBER OU SEJA E UM NUMERO
console.log(25, 123.45, 'João Pedro Moura Barboza') //PODEMOS EXIBIR TUDO NA MESMA LINHA 

